### ISSUE TITLE
WAS ID Critique

### ISSUE THREAD

**Issue by sishida** [OpenLiberty/draft-guide-springboot-mvc#1]
- The first instance of MVC (but not in the title) should be spelled out with "MVC" in parenthesis after: "model-view-controller (MVC)". Any other instances of MVC in the file can remain as "MVC".

- We try to stick with present tense as much as possible. Some future tense is OK in the "What you'll learn" section, but try to keep it to a bare minimum elsewhere.

- Avoid capitalizing words in the titles/section headings unless it's the first word or a product name. Capitalization for titles/headings in the guides are different than capitalization for, say, book titles.

- Avoid first person (I, me, we, our). Second person (you) is generally preferred.

- Do we need a section on recommended guides to try next (or is that generated elsewhere)?

**Comment by yeekangc** [comment]
@chyt, please take a look at Sarah's feedback above.

**Comment by chyt** [comment]
Updated based on this feedback. If a recommended guides section is generated, I don't think it should be in the guide.
