### ISSUE TITLE
Laura review comments

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/draft-guide-springboot-mvc#10]
Looks good. Mostly very clear what to do and I can see why it needs to be different. I think it makes sense in this case to be modifying the existing files because that's the whole point of the guide - modifying an existing app.

I know this isn't the final review but I've noted down anything that occurs to me as I go (I'm working through the app as I go, not just reading):

- [x] I like the abstract sentence - I know straight away what I'll get from the guide. 

- [x] Ditto the summary of the migration steps is nice and clear.

- [x] Can't remember what the style is but should the end of the Getting Started section include a step to stop the app (CTRL+C) so they don't accidentally leave it running?

- [ ] For consistency with the other guides and to show the point of the `finish` directory, is it worth adding a step saying that the `finish` directory contains the migrated app running on Open LIberty, run the `mvn install liberty:run-server` command to see the finished app? Feels a bit weird/lop-sided to show just a running app from the `start` directory but it's clear if there's an instruction to do the same from the `finish` directory too, I think... (and use the `run-server` option because that's the equivalent of the foreground command given for the Spring/Tomcat app).

- [x] The approach to modifying the `pom.xml` works okay I think. I know we try to avoid doing step-by-step (and I think we should in general still) but I think it works okay here. Can we highlight (in the asciidoc source) the lines that are being added in the whole `pom.xml` shown at the start of the section? Make it clear what the changes are then they can either just copy the whole `pom.xml` or they can do it manually if they like but there's a clear indicator as to where the new bits go.

- [x] I can't remember how the new side-by-side approach to the static guides works but can you just check this guide is okay for that too and won't require too much re-work?

- [x] 'Changing the packaging type' needs an example of the end result like the other steps, I think; eg

```
<groupId>io.openliberty.guides</groupId>
<artifactId>guide-spring-boot-mvc</artifactId>
<version>1.0-SNAPSHOT</version>
<packaging>liberty-assembly</packaging>
```

- [x] In VSCode at this point, I get this error: 
![image](https://user-images.githubusercontent.com/3322532/43833104-94dba158-9b01-11e8-8f04-cc8cc0699ab5.png)
`[Java] Project build error: Unknown packaging: liberty-assembly`

- [x] Minor thing: Remove "you’ll need to". Just say "add...".

- [x] Maybe re-word the lead-ins to the example end results as something like "Next, add the `<start-class>hello.Application</start-class>` property to the `<properties>` block:" or "Next, add the `<start-class>hello.Application</start-class>` property to the `<properties>` block:". Does that work?

 I'm actually using the copy button on the final result example because it's clear (having said "to the properties block" that that whole section is being updated). I don't know yet whether this still makes sense for larger elements with many lines....I'll see further down...

**Adding and modifying dependencies**
- [x] What does "transitively depends" mean?

- [x] Avoid using future tense. I think it's probably necessary to say "you need to" in this particular sentence but I think this whole paragraph could do with re-wording to be clearer anyway (see previous point). Can we avoid "Thus" - it's quite archaic.

- [x] I think it's possible to shorten this section so that there are fewer snippets. I would try removing the first snippet (that contains the bit to add) and wording the lead-in as: "Add an `<exclusion>` element to the `spring-boot-starter-thymeleaf` dependency:" then have just the `<dependency>` snippet. See what that looks like but I think it will be clear enough and it's easier to see what the snippets are for?

- [x] I found it difficult to read and get the point of the paragraph in general so I had a go at re-ordering it a bit. I appreciate how difficult this paragraph is to write! Here's what I attempted (the main thing is that I moved the point about Tomcat being default into the first sentence so that it's obvious from the start why something needs changing; I'm not sure if my use of terminology is absolutely correct but see what you think):

In the list of dependencies, the `spring-boot-starter-web` artifact uses Tomcat as the default embedded server. Tomcat needs to be excluded from the Maven build so that the app runs on Open Liberty instead. In the configuration for `spring-boot-starter-thymeleaf`, add an exclusion so that when the artifact calls `spring-boot-starter-web` it does not build Tomcat:

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-thymeleaf</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

- [x] "You can also remove the spring-boot-devtools dependency." add "because...." (why can it be removed and will things still work if you do not remove it?).

- [x] The Liberty Maven plugin entry - It looks really complicated having to replace two lines of Spring plugin config with all of this - how come Spring's is so simple in comparison? Is it because it's using the Spring parent pom?

- [x] Minor thing: "Finally, replace the spring-boot-maven-plugin configuration with the liberty-maven-plugin configuration." should end in a colon (:) to lead into the example end result.

**Changing the application startup process**
- [x] "Replace the original hello.Application class with the following code:" <- should that say Application class rather than hello.Application class? Ah no, I see. But for consistency with the other guides maybe give the full path of the file, rather than the logical class name. eg `src/ain/java/hello/Application.java` in the lead-in sentence before the snippet?

- [x] I think the way this is organised works well. I know we've tried to avoid modifying existing files but I think this is the whole point of this guide - updating an existing app with new code/config. And it seems clear enough to me how it works.

- [x] The intro to this section might need slight re-wording so it reads less like "it's easy with Spring but more complicated with OL" :) (re "simply" and "however") Don't make it too abstract but if you can make it sound a little more positive that'd be good.

- [x] When I run the app I get "Context not found". :(

**Comment by chyt** [comment]
- I don't think `changing the packaging type` needs an example of the completed snippet since it is a new addition. The default packaging type is overwritten. 

- The vscode issue is probably just because `liberty-assembly` is not a default packaging type. 

- "Transitively depends" is probably poorly worded. I meant that by depending on `spring-boot-starter-thymeleaf`, and by `spring-boot-starter-thymeleaf` depending on `spring-boot-starter-web`, you are transitively depending on `spring-boot-starter-web`. I've reworded this. 

- The liberty-maven-plugin config is more complicated since we are overwriting defaults to keep file structure standard with other OL guides, and because Spring does autoconfiguration. Also yes, some things could be simplified using the Liberty parent pom. 

- Removed "simply" for less of a stark contrast.

- Can you share your project so I can take a look? Or can you do a diff between it and the project in the `finish` folder to see what is missing?

Address all other checked off items in an incoming commit.

**Comment by evelinec** [comment]
@chyt are you going to handle the remaining 3 unchecked points?

**Comment by evelinec** [comment]
Reviewed all of the checked fixes, I found that the following areas may not be fixed according to feedback: 

- The paragraph describing adding the `<exclusions>` elements in the `<dependency>` block. 
- Specifying the full path of the `hello.Application` class 

@lauracowen would you take a look as well? Thank you.

**Comment by chyt** [comment]
@evelinec I have addressed both issues. The exclusion item was addressed by combining the `exclusion` snippet with the `dependency` snippet.

**Comment by evelinec** [comment]
@lauracowen would you review the fixes for your feedback and let us know if there's anything? Thanks.

**Comment by lauracowen** [comment]
Reading through the comments above, and chatting with Charles separately about the structure of the Modifying the POM section, I'm happy. Charles is going to tweak the ordering of the sub-sections within that section but otherwise looks good.

**Comment by evelinec** [comment]
I believe this issues had all been resolved.
