### ISSUE TITLE
More review on 7/16's draft

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-springboot-mvc#8]
- [x] :projectid: draft-guide-springboot-mvc => do not need to include "draft-guide-" in the project id. Just the name of the project, ie, springboot-mvc. This will impact the gitclone command. ie, this is what shows up currently: `git clone https://github.com/openliberty/guide-draft-guide-springboot-mvc.git`

- [x] The sample application that you will be migrating is Spring’s Serving Web Content with Spring MVC guide.  => this sentence is not right, ie, the sample app is the guide.. I think you'd like to refer to the sample app is **in the** guide.

- [x] The related guide attribute needs to be removed when there's no related guide, so the section doesn't appear in the website. 

- [x] Rename the name parameter "SpringBootApplication"

- [x] Make this url as a link instead of a copyable box for easier usage, ie, click to link: `http://localhost:8080/greeting?name=SpringBootApplication`

- [x] Use of the first person pronouns is to be avoided as per our guidelines in https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles: 
```
Use second person pronouns; limit first person pronouns.
Avoid using first person pronouns like 'we' and 'I' in guides. First person pronouns are generally unnecessary, and their identity is unclear.

Use "you" to refer to the reader, but this pronoun can also be unnecessary. For example, when giving instructions, state them in the imperative, such as, "Upload the file." The pronoun "you" is implied.
```

- [x] `src/test/resources/server.xml` => Why is server.xml in the `test` directory?

- [x] Create a src/test/resources/server.xml server configuration file (this is the default location defined by the configFile configuration parameter in the liberty-maven-plugin).
Add the following code to server.xml:
=> need to follow the guideline of creating a new file, see link above. 

- [x] The code snippet with the "..." is confusing. They don't meant to be copied directly, right? 
```
<properties>
   ...
    <start-class>hello.Application</start-class>
    ...
</properties>
```

**Comment by evelinec** [comment]
Follow up issues: 

- [x] The path "src/test/resources/server.xml" is not updated in the readme.adoc. Did you move the server.xml file to somewhere else, as we discussed? Nonetheless, the directory to the file to be created is best to be provided to user. ie, the "src/test/resources" folder should be pre-created in the start folder. 

- [x] Create a src/test/resources/server.xml server configuration file (this is the default location defined by the configFile configuration parameter in the liberty-maven-plugin): => It's better remove the (). 

- [x] Traditionally, a Spring Boot application running on an embedded server such as Tomcat simply calls SpringApplication.run(…​) in its main class (in this case hello.Application). => same here for the () of text. It's better to state the content without using (). 

- [x]  Replace the original class with the following code: => Just reading this, not sure which class to replace the code with. Can you include the path to the class that user is to modify? 

- [x] Now verify that your Spring Boot application is running in Open Liberty. Navigate to the following URL (notice that the port has changed to 9080): => same here for the usage of ().

**Comment by chyt** [comment]
```
Create a src/test/resources/server.xml server configuration file (this is the default location defined by the configFile configuration parameter in the liberty-maven-plugin): => It's better remove the ().
```

Removed this sentence since we are no longer using the default. 

```
Replace the original class with the following code: => Just reading this, not sure which class to replace the code with. Can you include the path to the class that user is to modify?
```

Included the class name with package (`hello.Application`).

**Comment by evelinec** [comment]
Regarding pre-creating the folders, I understand why you want to leave it that way. To have the `src/main/liberty/config` folders precreated is to help with user working through the guide. Basically, if the folders are created, they can just create the file in one command, otherwise, it’ll be 3 steps, ie, 2 steps to create the `liberty` and `config` folders, and the other to create the file. This is just to explain the user experience to you. It’s recommended from the guide’s perspective to pre-create all necessary folders to help with user experiences; there may be less technical people who may make mistake in this steps and then complain. It’s up to you to make the changes. Thanks.

**Comment by evelinec** [comment]
The `src/main/liberty/config` folder is not pre-created.
