### ISSUE TITLE
New issues on draft and guide

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-springboot-mvc#9]
- [x] For the server.xml file, regarding line `The servlet-3.1 feature is also needed for running the application, as well as other items which are described in the XML comments.` It’s recommended to have the explanation in the guide instead of in the comments. There are couple reasons, one to keep the code clean, and second, our guides are meant to be conversational focus, not so technical focus to have user to follow the code.
New: `Replace the original hello.Application class with the following code:` => It’s recommended to include the full path of the `hello.Application` class, ie, `src/main/java/hello/Application.java`. Some user may not be able to find that file (I think that’s the one) by reading `hello.Application` class.

- [x] Got this error after working the guide on the `start` directory and run the `mvn liberty:start-server` command. Error in the console.log:

 ```
[ERROR   ] CWWKG0014E: The configuration parser detected an XML syntax error while parsing the root of the configuration and the referenced configuration documents. Error: The processing instruction target matching "[xX][mM][lL]" is not allowed. File: file:/Users/evelinec/OLG/testing/draft-guide-springboot-mvc/start/target/liberty/wlp/usr/servers/MVCServer/server.xml Line: 3 Column: 6
[WARNING ] CWWKF0009W: The server has not been configured to install any features.
[AUDIT   ] CWWKF0011I: The server MVCServer is ready to run a smarter planet.
```

- [x] I think the duration of this guide doesn't need 30 minutes. 15 - 20 minutes is good.

**Comment by chyt** [comment]
Regarding the XML syntax error, are you sure you copied the server.xml properly? Log says that it is complaining about line 3, which in the original source is

```
<application context-root="/"
        location="guide-spring-boot-mvc.war"></application>
```

**Comment by evelinec** [comment]
I figured out the problem about the xml syntax error. Basically, the problem is if the xml file starts with empty lines, then compilation will fail with xml syntax error. In working through this guide, somehow, when copy the snippets of code or classes to create a file, there's always 2 empty line added at the beginning of the file. This is not good for xml files. However, doesn't look like there's any solution for this. 

Secondly, most of the code snippets in the `readme.adoc` file were pasted directly on the file. This is not good. Use the following asciidoc syntax to include section of code from a file. 

1. Use include with tags to include code snippets.

Example from the CDI-intro guide: https://raw.githubusercontent.com/OpenLiberty/guide-cdi-intro/master/README.adoc

```
[source, Java]
----
include::finish/src/main/java/io/openliberty/guides/inventory/InventoryResource.java[tags=**;!copyright]
----
```

2. Use `source` with type to identify the type of file included. Example:

```
[source,xml,indent=0, role="no_copy"]
----
include::finish/pom.xml[tag=bootstrap]
----
```

**Comment by evelinec** [comment]
FYI, I still see `hello.Application` path being used in the 8/30's draft.

**Comment by evelinec** [comment]
Talked to @chyt to address the other 3 pasted code snippets in the readme.

**Comment by evelinec** [comment]
Resolved.
